# Generated by Django 2.2.4 on 2019-10-13 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.CharField(default=utils.uuid.generate_uuid, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('proprietor', models.CharField(max_length=255)),
                ('tenure', models.CharField(max_length=255)),
                ('tenure_volume', models.CharField(max_length=255)),
                ('tenure_folio_no', models.CharField(max_length=255)),
                ('size_of_land', models.CharField(max_length=255)),
                ('lease_period', models.CharField(max_length=255)),
                ('lease_authority', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('parish', models.CharField(max_length=255)),
                ('block', models.CharField(max_length=255)),
                ('plot', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('district', 'parish', 'block', 'plot')},
            },
        ),
    ]
